title: Harsh Bhimjyani
url: "https://harshvb7.github.io"
description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""

info:
  github: "https://github.com/harshvb7"
  medium: "https://medium.com/@harshvb7"
  linkedin: "https://linkedin.com/in/harshbhimjyani"
  twitter: "https://twitter.com/HarshBhimjyani"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock